[package]
name = "obs-cmd"
version = "0.19.1"
edition = "2021"
description = "A minimal command to control obs via obs-websocket"
authors = ["Luigi Maselli <luigi@grigio.org>"]
rust-version = "1.88.0"

[[bin]]
name = "obs-cmd"

[dependencies]
tokio = { version = "1.45.0", features = ["rt-multi-thread", "macros"] }
obws = "0.14.0"
clap = { version = "4.5.39", features = ["derive"] }
url = "2.5.4"
time = "0.3.41"
