name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  desktop:
    strategy:
      fail-fast: false
      matrix:
        os: [debian-latest, macos-latest, windows-latest]
        include:
          - os: debian-latest
            artifact_name: ./target/release/obs-cmd
            asset_name: obs-cmd-linux-amd64
          
          - os: windows-latest
            artifact_name: ./target/release/obs-cmd.exe
            asset_name: obs-cmd-windows-amd64.exe
          
          - os: macos-latest
            artifact_name: ./target/release/obs-cmd
            asset_name: obs-cmd-macos-amd64

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --release

    - name: Upload binaries
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

  embedded:
    runs-on: debian-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Install cross
      run: cargo install cross

    - name: Build for aarch64-unknown-linux-gnu
      run: cross build --target aarch64-unknown-linux-gnu --release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/aarch64-unknown-linux-gnu/release/obs-cmd
        asset_name: obs-cmd-aarch64-linux
        tag: ${{ github.ref }}
